credentials:
  usernames:
    annamalai:
      email: anna@gmail.com
      name: Annamalai V R
      password: $2b$12$/Tst533PJcMDuv1pcUyik.BtBlDSI4wKNBnMbC43i5cySfPJiOiuG
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$7eoCtrZpoXsckhlob.5sD.dpynsOn5mpdffn5M0Gm0.VnVO5t5qya
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
